package menu;

import java.awt.Cursor;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import koneksi.koneksi;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

public class menu_crud extends javax.swing.JFrame {
public final Connection conn = new koneksi().connect();
    private DefaultTableModel tabmode;
    
    
    private void aktif(){
        txtFieldMerek.setEnabled(true);
        txtFieldTipe.setEnabled(true);
        txtFieldNoPolisi.setEnabled(true);
        txtFieldHarga.setEnabled(true);       
    }
   
    protected void kosong(){
        txtFieldMerek.setText(null);
        txtFieldTipe.setText(null);
        txtFieldNoPolisi.setText(null);
        txtFieldHarga.setText(null);
    }
    
    public void noId(){
        int Baris = tabmode.getRowCount();
        for(int a = 0; a< Baris; a++){
            String nomor = String.valueOf(a+1);
            tabmode.setValueAt(nomor + ".",a, 0);
        }
    }

    public void LebarKolom(){
        TableColumn kolom;
        mb_tb.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        kolom = mb_tb.getColumnModel().getColumn(0);
        kolom.setPreferredWidth(40);
        kolom = mb_tb.getColumnModel().getColumn(1);
        kolom.setWidth(150);
        kolom = mb_tb.getColumnModel().getColumn(2);
        kolom.setWidth(150);
        kolom = mb_tb.getColumnModel().getColumn(3);
        kolom.setWidth(150);
        kolom = mb_tb.getColumnModel().getColumn(4);
        kolom.setWidth(150);
        kolom = mb_tb.getColumnModel().getColumn(5);
        kolom.setWidth(150); 
        kolom = mb_tb.getColumnModel().getColumn(6);
        kolom.setWidth(150); 
      
    }
    public void dataTable(){
        Object [] Baris = {"ID","Merek","Tipe","Tahun","No.Polisi","Harga", "Status"};
        tabmode = new DefaultTableModel (null, Baris);
        mb_tb.setModel(tabmode);
        String sql = "select*from tb_addcar";
        try{
            java.sql.Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            while (hasil.next()){
                String mrk = hasil.getString("merek");
                String tp = hasil.getString("tipe");
                String thn = hasil.getString("tahun");
                String nopls = hasil.getString("nopolisi");
                String hrg = hasil.getString("harga");
                String stts = hasil.getString("status");
                String [] data = {"", mrk, tp, thn, nopls,hrg,stts};
                tabmode.addRow(data);
                noId();
                LebarKolom();
            }
            
        }catch (Exception e){
            
        }
        
    }
  
    public void pencarian(String sql){
        Object [] Baris = {"ID","Merek","Tipe","Tahun","No.Polisi","Harga", "Status"};
        tabmode = new DefaultTableModel (null, Baris);
        mb_tb.setModel(tabmode);
        int brs = mb_tb.getRowCount();
        for(int i = 0; 1<brs; i++){
            tabmode.removeRow(1);
    } 
        try {
             java.sql.Statement stat = conn.createStatement();
             ResultSet hasil = stat.executeQuery(sql);
             while (hasil.next()){
                String mrk = hasil.getString("merek");
                String tp = hasil.getString("tipe");
                String thn = hasil.getString("tahun");
                String nopls = hasil.getString("nopolisi");
                String hrg = hasil.getString("harga");
                String stts = hasil.getString("status");
                String [] data = {"", mrk, tp, thn, nopls,hrg,stts};
                tabmode.addRow(data);
                noId();
             }
 
    } catch (Exception e) {
        
    }
        
    }
    public menu_crud() {
        initComponents();
        setLocationRelativeTo(null);
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        hideLabel_forButtonClick();
        dataTable();
        LebarKolom();
        aktif();
        kosong();
        txtFieldMerek.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    
    private void hideLabel_forButtonClick(){
        clickAdd.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        clickUpdate.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        clickSearch.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        clickDelete.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        goToHome.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtFieldHarga = new javax.swing.JTextField();
        txtFieldMerek = new javax.swing.JTextField();
        txtFieldTipe = new javax.swing.JTextField();
        txtFieldNoPolisi = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        mb_tb = new javax.swing.JTable();
        goToHome = new javax.swing.JLabel();
        clickDelete = new javax.swing.JLabel();
        clickAdd = new javax.swing.JLabel();
        clickUpdate = new javax.swing.JLabel();
        clickSearch = new javax.swing.JLabel();
        BoxKetersediaan = new javax.swing.JComboBox<>();
        boxThnProduksi = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CRUD Menu");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtFieldHarga.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        txtFieldHarga.setBorder(null);
        txtFieldHarga.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFieldHargaActionPerformed(evt);
            }
        });
        getContentPane().add(txtFieldHarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 300, 240, 30));

        txtFieldMerek.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        txtFieldMerek.setBorder(null);
        getContentPane().add(txtFieldMerek, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 150, 240, 30));

        txtFieldTipe.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        txtFieldTipe.setBorder(null);
        getContentPane().add(txtFieldTipe, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 200, 240, 30));

        txtFieldNoPolisi.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        txtFieldNoPolisi.setBorder(null);
        getContentPane().add(txtFieldNoPolisi, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 250, 240, 30));

        mb_tb.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Merek", "Tipe", "Tahun", "No. Polisi", "Harga ", "Status"
            }
        ));
        mb_tb.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mb_tbMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(mb_tb);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 480, 890, 230));

        goToHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                goToHomeMouseClicked(evt);
            }
        });
        getContentPane().add(goToHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, 100, 110));

        clickDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clickDeleteMouseClicked(evt);
            }
        });
        getContentPane().add(clickDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 360, 163, 60));

        clickAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clickAddMouseClicked(evt);
            }
        });
        getContentPane().add(clickAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 360, 160, 60));

        clickUpdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clickUpdateMouseClicked(evt);
            }
        });
        getContentPane().add(clickUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 360, 160, 60));

        clickSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clickSearchMouseClicked(evt);
            }
        });
        getContentPane().add(clickSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 360, 163, 60));

        BoxKetersediaan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ada", "Tidak ada" }));
        getContentPane().add(BoxKetersediaan, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 300, 120, 30));

        boxThnProduksi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2009", "2012", "2015", "2019", "2020" }));
        boxThnProduksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxThnProduksiActionPerformed(evt);
            }
        });
        getContentPane().add(boxThnProduksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 260, 120, 30));

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel1.setText("Tahun Produksi");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 260, -1, 30));

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel2.setText("Ketersediaan");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 300, -1, 30));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/menu_crud.png"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 1360, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void clickAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clickAddMouseClicked

       if (txtFieldMerek.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Merek Mobil Tidak Boleh Kosong");
        } else if (txtFieldTipe.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Tipe Mobil Tidak Boleh Kosong");
        } else if (txtFieldNoPolisi.getText().equals("")){
            JOptionPane.showMessageDialog(null,"No Polisi Tidak Boleh Kosong");
        } else if (txtFieldHarga.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Harga Tidak Boleh Kosong");
        } 
        else {
       
        String sql = "insert into tb_addcar values (?,?,?,?,?,?)";
            try{
                PreparedStatement stat = conn.prepareStatement(sql);
                stat.setString(1, txtFieldMerek.getText());
                stat.setString(2, txtFieldTipe.getText());
                stat.setString(3, (String) boxThnProduksi.getSelectedItem());
                stat.setString(4, txtFieldNoPolisi.getText());
                stat.setString(5, txtFieldHarga.getText());
                stat.setString(6, (String) BoxKetersediaan.getSelectedItem());
                stat.executeUpdate();
                
                JOptionPane.showMessageDialog(null,"Data Berhasil Disimpan");
                kosong();
                dataTable();
                LebarKolom();
                noId();
                txtFieldMerek.requestFocus();
            } catch (SQLException e){
                JOptionPane.showMessageDialog(null, "Data Gagal Disimpan"+ e);
            }
        }       
    }//GEN-LAST:event_clickAddMouseClicked

    private void clickUpdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clickUpdateMouseClicked
   
   int ok = JOptionPane.showConfirmDialog(null, "Apakah Anda Yakin" + " Ingin Mengubah Data", "Konfirmasi Dialog", JoptionPane.YES_NO_OPTION);
        if (ok == 0){
            String sql = "update tb_addcar set merek=?, tipe=?,tahun=?,nopolisi=?,harga=?,status=? where nopolisi ='" + txtFieldNoPolisi.getText() + "'"; 
             try{
                PreparedStatement stat = conn.prepareStatement(sql);
                stat.setString(1, txtFieldMerek.getText());
                stat.setString(2, txtFieldTipe.getText());
                stat.setString(3, (String) boxThnProduksi.getSelectedItem());
                stat.setString(4, txtFieldNoPolisi.getText());
                stat.setString(5, txtFieldHarga.getText());
                stat.setString(6, (String) BoxKetersediaan.getSelectedItem());
                stat.executeUpdate();
                
                JOptionPane.showMessageDialog(null,"Data Berhasil Diubah");
                kosong();
                dataTable();
                LebarKolom();
                noId();
                txtFieldMerek.requestFocus();
            } catch (SQLException e){
                JOptionPane.showMessageDialog(null, "Data Gagal Diubah"+ e);
            }
        }
    }//GEN-LAST:event_clickUpdateMouseClicked

    private void clickSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clickSearchMouseClicked
        String sqlPencarian = "select * from add_car where merek like '%" + clickSearch.getText()+ "%' or "
        + "tipe like '%" + clickSearch.getText() + "%' or "
        + "nopolisi '%" + clickSearch.getText() + "%'";
        pencarian(sqlPencarian);
        LebarKolom();
        dataTable();
    }//GEN-LAST:event_clickSearchMouseClicked

    private void clickDeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clickDeleteMouseClicked
     
        int ok = JOptionPane.showConfirmDialog(null, "Apakah Anda Yakin" + " Ingin Menghapus Data", "Konfirmasi Dialog", JoptionPane.YES_NO_OPTION);
        if (ok == 0){
            String sql = "delete from tb_addcar where nopolisi ='"+txtFieldNoPolisi.getText()+"'"; 
            try {
                PreparedStatement stat = conn.prepareStatement(sql);
                stat.executeUpdate();
                JOptionPane.showMessageDialog(null, "Data Berhasil Dihapus");
                kosong();
                dataTable();
                LebarKolom();
                txtFieldMerek.requestFocus();
            }catch (SQLException e){
                JOptionPane.showMessageDialog(null, "Data Gagal Dihapus" + e);
            }
        }
    }//GEN-LAST:event_clickDeleteMouseClicked

    private void goToHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_goToHomeMouseClicked
        // TODO add your handling code here:
        menu_utama utama = new menu_utama();
        utama.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_goToHomeMouseClicked

    private void boxThnProduksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxThnProduksiActionPerformed
        
    }//GEN-LAST:event_boxThnProduksiActionPerformed

    private void mb_tbMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mb_tbMouseClicked
        int bar = mb_tb.getSelectedRow();
        
        String b = tabmode.getValueAt(bar, 1).toString();
        String c = tabmode.getValueAt(bar, 2).toString();
        String d = tabmode.getValueAt(bar, 3).toString();
        String e = tabmode.getValueAt(bar, 4).toString();
        String f = tabmode.getValueAt(bar, 5).toString();
        String g = tabmode.getValueAt(bar, 6).toString();
      
        txtFieldMerek.setText(b);
        txtFieldTipe.setText(c);
        boxThnProduksi.setSelectedItem(d);
        txtFieldNoPolisi.setText(e);
        txtFieldHarga.setText(f);
        BoxKetersediaan.setSelectedItem(g);
        
        
    }//GEN-LAST:event_mb_tbMouseClicked

    private void txtFieldHargaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFieldHargaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFieldHargaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu_crud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu_crud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu_crud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu_crud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu_crud().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> BoxKetersediaan;
    private javax.swing.JLabel background;
    private javax.swing.JComboBox<String> boxThnProduksi;
    private javax.swing.JLabel clickAdd;
    private javax.swing.JLabel clickDelete;
    private javax.swing.JLabel clickSearch;
    private javax.swing.JLabel clickUpdate;
    private javax.swing.JLabel goToHome;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable mb_tb;
    private javax.swing.JTextField txtFieldHarga;
    private javax.swing.JTextField txtFieldMerek;
    private javax.swing.JTextField txtFieldNoPolisi;
    private javax.swing.JTextField txtFieldTipe;
    // End of variables declaration//GEN-END:variables

    
}
