/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package menu;

import java.awt.Cursor;

/**
 *
 * @author ASUS
 */
public class menu_utama extends javax.swing.JFrame {

    /**
     * Creates new form menu_utama
     */
    public menu_utama() {
        initComponents();
        setLocationRelativeTo(null);
        btnMenuInvisibility();
        pointerChanges();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    private void btnMenuInvisibility(){
        btnDatabase.setOpaque(false);
        btnDatabase.setContentAreaFilled(false);
        btnDatabase.setBorderPainted(false);
        
        btnRent.setOpaque(false);
        btnRent.setContentAreaFilled(false);
        btnRent.setBorderPainted(false);
    }
    
    private void pointerChanges(){
        btnDatabase.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        btnRent.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        
        goToHome.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        aboutUs.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        
        
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRent = new javax.swing.JButton();
        aboutUs = new javax.swing.JLabel();
        goToHome = new javax.swing.JLabel();
        btnDatabase = new javax.swing.JButton();
        menuUtamaDesign = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(btnRent, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 150, 190, 240));
        getContentPane().add(aboutUs, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 430, 60, 80));
        getContentPane().add(goToHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 30, 60, 70));
        getContentPane().add(btnDatabase, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 150, 190, 240));

        menuUtamaDesign.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/menu_utama .png"))); // NOI18N
        getContentPane().add(menuUtamaDesign, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu_utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu_utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu_utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu_utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu_utama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel aboutUs;
    private javax.swing.JButton btnDatabase;
    private javax.swing.JButton btnRent;
    private javax.swing.JLabel goToHome;
    private javax.swing.JLabel menuUtamaDesign;
    // End of variables declaration//GEN-END:variables
}
