/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package menu;

import java.awt.Cursor;
import javax.swing.JFrame;

/**
 *
 * @author ASUS
 */
public class menu_crud extends javax.swing.JFrame {

    /**
     * Creates new form menu_crud
     */
    public menu_crud() {
        initComponents();
        setLocationRelativeTo(null);
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        hideLabel_forButtonClick();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    
    private void hideLabel_forButtonClick(){
        clickAdd.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        clickUpdate.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        clickSearch.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        clickDelete.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        goToHome.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtFieldHarga = new javax.swing.JTextField();
        txtFieldMerek = new javax.swing.JTextField();
        txtFieldTipe = new javax.swing.JTextField();
        txtFieldNoPolisi = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        goToHome = new javax.swing.JLabel();
        clickDelete = new javax.swing.JLabel();
        clickAdd = new javax.swing.JLabel();
        clickUpdate = new javax.swing.JLabel();
        clickSearch = new javax.swing.JLabel();
        BoxKetersediaan = new javax.swing.JComboBox<>();
        boxThnProduksi = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CRUD Menu");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtFieldHarga.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        txtFieldHarga.setBorder(null);
        getContentPane().add(txtFieldHarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 300, 240, 30));

        txtFieldMerek.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        txtFieldMerek.setBorder(null);
        getContentPane().add(txtFieldMerek, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 150, 240, 30));

        txtFieldTipe.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        txtFieldTipe.setBorder(null);
        getContentPane().add(txtFieldTipe, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 200, 240, 30));

        txtFieldNoPolisi.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        txtFieldNoPolisi.setBorder(null);
        getContentPane().add(txtFieldNoPolisi, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 250, 240, 30));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Merek", "Tipe", "Tahun", "No. Polisi", "Harga ", "Status"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 480, 890, 230));

        goToHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                goToHomeMouseClicked(evt);
            }
        });
        getContentPane().add(goToHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, 100, 110));

        clickDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clickDeleteMouseClicked(evt);
            }
        });
        getContentPane().add(clickDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(1050, 360, 163, 60));

        clickAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clickAddMouseClicked(evt);
            }
        });
        getContentPane().add(clickAdd, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 360, 160, 60));

        clickUpdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clickUpdateMouseClicked(evt);
            }
        });
        getContentPane().add(clickUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 360, 160, 60));

        clickSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clickSearchMouseClicked(evt);
            }
        });
        getContentPane().add(clickSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 360, 163, 60));

        BoxKetersediaan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ada", "Tidak ada" }));
        getContentPane().add(BoxKetersediaan, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 300, 120, 30));

        boxThnProduksi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2009", "2012", "2015", "2019", "2020" }));
        getContentPane().add(boxThnProduksi, new org.netbeans.lib.awtextra.AbsoluteConstraints(1100, 260, 120, 30));

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel1.setText("Tahun Produksi");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(970, 260, -1, 30));

        jLabel2.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel2.setText("Ketersediaan");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 300, -1, 30));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/menu_crud.png"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void clickAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clickAddMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_clickAddMouseClicked

    private void clickUpdateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clickUpdateMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_clickUpdateMouseClicked

    private void clickSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clickSearchMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_clickSearchMouseClicked

    private void clickDeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clickDeleteMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_clickDeleteMouseClicked

    private void goToHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_goToHomeMouseClicked
        // TODO add your handling code here:
        menu_utama utama = new menu_utama();
        utama.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_goToHomeMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu_crud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu_crud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu_crud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu_crud.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu_crud().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> BoxKetersediaan;
    private javax.swing.JLabel background;
    private javax.swing.JComboBox<String> boxThnProduksi;
    private javax.swing.JLabel clickAdd;
    private javax.swing.JLabel clickDelete;
    private javax.swing.JLabel clickSearch;
    private javax.swing.JLabel clickUpdate;
    private javax.swing.JLabel goToHome;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtFieldHarga;
    private javax.swing.JTextField txtFieldMerek;
    private javax.swing.JTextField txtFieldNoPolisi;
    private javax.swing.JTextField txtFieldTipe;
    // End of variables declaration//GEN-END:variables
}
